## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.url: jdbc:postgresql://localhost:5432/kafka_example
spring.datasource.username: kafka_example
spring.datasource.password: 6iJ7RyW!yc!xmXW^

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto: none
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
